name: gi_card
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true


  assets:
    - images/Fayasal.jpg

  fonts:
    -  family: RubikWetPaint
       fonts:
         - asset: fonts/RubikWetPaint-Regular.ttf

    - family: TiroBangla
      fonts:
        - asset: fonts/TiroBangla-Italic.ttf